//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JBMapp.ADUC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActiveDirectoryWebSoap", Namespace="http://tempuri.org/")]
    public partial class ActiveDirectoryWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchActiveDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmployeeGovernmentIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActiveDirectoryWeb() {
            this.Url = global::JBMapp.Properties.Settings.Default.JBMapp_ADUC_ActiveDirectoryWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchActiveDirectoryCompletedEventHandler SearchActiveDirectoryCompleted;
        
        /// <remarks/>
        public event GetEmployeeGovernmentIDCompletedEventHandler GetEmployeeGovernmentIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchActiveDirectory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchActiveDirectory(string uName) {
            object[] results = this.Invoke("SearchActiveDirectory", new object[] {
                        uName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchActiveDirectoryAsync(string uName) {
            this.SearchActiveDirectoryAsync(uName, null);
        }
        
        /// <remarks/>
        public void SearchActiveDirectoryAsync(string uName, object userState) {
            if ((this.SearchActiveDirectoryOperationCompleted == null)) {
                this.SearchActiveDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchActiveDirectoryOperationCompleted);
            }
            this.InvokeAsync("SearchActiveDirectory", new object[] {
                        uName}, this.SearchActiveDirectoryOperationCompleted, userState);
        }
        
        private void OnSearchActiveDirectoryOperationCompleted(object arg) {
            if ((this.SearchActiveDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchActiveDirectoryCompleted(this, new SearchActiveDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmployeeGovernmentID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmployeeGovernmentID(string eID) {
            object[] results = this.Invoke("GetEmployeeGovernmentID", new object[] {
                        eID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployeeGovernmentIDAsync(string eID) {
            this.GetEmployeeGovernmentIDAsync(eID, null);
        }
        
        /// <remarks/>
        public void GetEmployeeGovernmentIDAsync(string eID, object userState) {
            if ((this.GetEmployeeGovernmentIDOperationCompleted == null)) {
                this.GetEmployeeGovernmentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeGovernmentIDOperationCompleted);
            }
            this.InvokeAsync("GetEmployeeGovernmentID", new object[] {
                        eID}, this.GetEmployeeGovernmentIDOperationCompleted, userState);
        }
        
        private void OnGetEmployeeGovernmentIDOperationCompleted(object arg) {
            if ((this.GetEmployeeGovernmentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeGovernmentIDCompleted(this, new GetEmployeeGovernmentIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SearchActiveDirectoryCompletedEventHandler(object sender, SearchActiveDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchActiveDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchActiveDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetEmployeeGovernmentIDCompletedEventHandler(object sender, GetEmployeeGovernmentIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeGovernmentIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployeeGovernmentIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591